import { Inter } from "next/font/google";
import "./globals.css";
import NotesProvider, { NotesContext } from "./context/note";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Note Taking Web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotesProvider>
          {children}
        </NotesProvider>
      </body>
    </html>
  );
}
